apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      # Apunta al puerto nombrado del contenedor (containerPort).
      targetPort: http
